### ISSUE TITLE
🚀 Feature: GitHub A11y bot for alt text

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [appwrite/pink#112]
### 🔖 Feature description

You should add [https://github.com/github/accessibility-alt-text-bot](url), or have another way (I'll volunteer!) to add alt-text to your images for accessibility. 

### 🎤 Pitch

Since appwrite/pink is accessibility forward, alt-text on images is imperative to meet compliance standards. If you don't want to add a bot, I volunteer to make pull requests to add alt-text to your images. Accessibility is my thing. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shivanshu814** [comment]
Can I Also Contribute In It? ! @Emmarie-Ahtunan

**Comment by Emmarie-Ahtunan** [comment]
@shivanshu814, it's not my issue/feature to assign. I am making a suggestion. Best!

**Comment by TorstenDittmann** [comment]
Interesting, didn't knew such an action exists 👀 

Go ahead and feel free to contribute it to pink, will be a good guinea pig repo to potentially add it to other repos too.
