### ISSUE TITLE
🐛 Bug Report: Broken link inf design secrtion of homeopage

### ISSUE THREAD

**Issue by ItsRoy69** [appwrite/pink#28]
### 👟 Reproduction steps

When we move to the site and scroll down, we confront "design" section where there is "storage" button. As we click on the button we see it is getting redirected to https://pink.appwrite.io/users.html which shows 
![image](https://user-images.githubusercontent.com/78967360/214626582-b9b4311d-8bee-495b-8dd9-11af704db030.png)

### 👍 Expected behavior

As we click on other buttons of design section we see it gets redirected to the homepage and thus it needs to change in this button too.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/78967360/214627236-b6ac36dc-286b-4f6f-8d49-6cb4623bc56a.png)
This happened

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Thank you for reporting, fixing it now 🙏🏻
