### ISSUE TITLE
🐛 Bug Report: File Upload Box progress indicator stretches horizontally

### ISSUE THREAD

**Issue by marcospampi** [appwrite/pink#31]
### 👟 Reproduction steps

I found this unwanted feature while exploring the [showcases](https://pink.appwrite.io/components/upload-box) in the main website.

Apparently, if the horizontal space is limited, the component gets stretched, so just open the link and shrink the browser window to reproduce this.

### 👍 Expected behavior

Not to stretch.

### 👎 Actual Behavior

Ok, viewport not too stretched so there's enough space to grow:
![wanted behavior](https://i.imgur.com/J41Tqo4.png)

YACK!
![unwanted behaviour](https://i.imgur.com/QH5zPFH.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@marcospampi, thanks for creating this issue! 🙏🏼 we'll look into this soon!

**Comment by elad2412** [comment]
@marcospampi, we added fixed; you can check it now.

If there is any comment, please let us know :-)

Closed Issue.
