### ISSUE TITLE
📚 Documentation: The "Getting Started" page has an invalid npm install

### ISSUE THREAD

**Issue by singularitysoft** [appwrite/pink#34]
### 💭 Description

`npm install @appwrite.io/pink` doesn't work. It yields the following error:

```
+ npm install @appwrite.io/pink
+             ~~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@appwrite' can be used only as an argument to a
command. To reference variables in an expression use '$appwrite'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

This is also true of the repository's readme. Fortunately, all you need to do to fix this is enclose the package name in quotes as follows: `npm install "@appwrite.io/pink"`. I'll make a pull request with this change for your convenience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TGlide** [comment]
This is curious, as I've tested it on different shells (fish, bash, etc.) and it works. Would you mind sharing your shell and/or Operating System?

Regardless, the quoted version also works, so a PR is more than welcome :smile:
