### ISSUE TITLE
🐛 Bug Report: Cannot apply dark theme

### ISSUE THREAD

**Issue by singularitysoft** [appwrite/pink#39]
### 👟 Reproduction steps

When I add `$theme-dark: ".theme-dark";` to my CSS, the application stops working. See attached image. Note that I included the `lang="scss"` attribute in the style tag.

<img width="816" alt="0" src="https://user-images.githubusercontent.com/124126097/216030097-f2266b63-97f9-49af-8e02-6699c5447c7d.png">

I am using Windows 11 but will test on Linux and update my findings.

### 👍 Expected behavior

Apply the dark theme to the app

### 👎 Actual Behavior

Application errors out

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TGlide** [comment]
Could you add more details, e.g. what type of project are you using? I saw you're using Vite, are you using any specific JS framework, or vanilla JS?

I tried reproducing the error on a SvelteKit project, but failed to trigger an error: https://github.com/TGlide/pink-repro.

If you provide more details, or link to an existing project where the issue occurs, I'll do my best to assist you :slightly_smiling_face:

**Comment by TGlide** [comment]
Closing due to inactive and no reproductions
