### ISSUE TITLE
📚 Documentation: Clicking a button inside input refreshes the page

### ISSUE THREAD

**Issue by mat2ja** [appwrite/pink#45]
### 💭 Description

On [`elements/input-fields`](https://pink.appwrite.io/elements/input-field) page, clicking a button inside the input field (i.e. to show/hide password, or copy text) causes a whole page refresh.

This happens because most of the input field examples are inside a form, so a button click submits the form by default. The issue would be resolved by setting `type="button"` on all of these buttons.

```html
<form class="form u-width-full-line u-max-width-500">
  <ul class="form-list">
    <li class="form-item">
      <label class="label">Label</label>
      <div class="input-text-wrapper">
        <input type="password" class="input-text" placeholder="Placeholder" />
        <button
          class="show-password-button"
          aria-label="show password"
          type="button"
        >
          <span class="icon-eye" aria-hidden="true"></span>
        </button>
      </div>
    </li>
    ...
  </ul>
</form>
```

I have a PR ready if all this sounds alright 😄

As for the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md) below, I'm getting a 404. [This](https://github.com/appwrite/.github/blob/707fb2493c1c8b5150904e1eb2e2e3ed71aad501/CODE_OF_CONDUCT.md) seems to be the correct link.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@mat2ja nice catch, thank you :+1:
