### ISSUE TITLE
📚 Documentation: Input field icon overlapping input text

### ISSUE THREAD

**Issue by mat2ja** [appwrite/pink#47]
### 💭 Description

Some of the input fields on [`elements/input-fields`](https://pink.appwrite.io/elements/input-field) page have text overlapping with the icon, and with a icon coming from an external source (1Password Chrome extension in this case). Basically, it needs some padding on the right to accommodate the icon.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/46557266/216158550-3e33e2da-9ef1-429c-bf40-78814d7a4922.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/46557266/216158588-deaf9ca5-33c8-4822-b9de-dd4c799895ef.png">

I classified this as a documentation issue instead of a bug, as it seems there already is a way to handle this, via `style="--amount-of-buttons:1"` property, it just wasn't applied to these specific examples.

Although, in the last input example, problem is solved by using a `u-padding-indline-end-56` class, instead of using that `--amount-of-buttons` custom property. Which of the 2 approaches is the recommended one? 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@mat2ja thank you for creating this issue and a PR :pray:  

The `--amount-of-buttons` is the correct solution :+1:
