### ISSUE TITLE
🐛 Bug Report: Poor legibility/contrast of text selected in code panel when in dark theme

### ISSUE THREAD

**Issue by BadgerHobbs** [appwrite/pink#49]
### 👟 Reproduction steps

- Dark theme is enabled
- User selects code panel with syntax highlighting
- Code has low contrast to selection background, and poor legibility

See dark and light mode comparison below.

![image](https://user-images.githubusercontent.com/23462440/216168393-0f695062-9cb0-4c44-8796-e45844f500b1.png)

![image](https://user-images.githubusercontent.com/23462440/216168401-1e54ebe4-ced1-4ce9-a3cf-6718c3f0df0b.png)

### 👍 Expected behavior

The expectation based on usual best practices is that the highlighted text would be something to contrast directly with the highlight/selection colour (the purple is just an example).

![image](https://user-images.githubusercontent.com/23462440/216170144-d57e1cb0-8bf7-484d-9fc1-d00b047bc7e4.png)

### 👎 Actual Behavior

Screenshot of example when in dark theme.

![image](https://user-images.githubusercontent.com/23462440/216168393-0f695062-9cb0-4c44-8796-e45844f500b1.png)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Pink v0.0.2 via unpkg CDN.
Windows 10
Chrome and Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@BadgerHobbs thank you for creating this issue :pray: we'll definitely take a look into this :)
