### ISSUE TITLE
🐛 Bug Report: scrollbar appears on phone chrome dev tools

### ISSUE THREAD

**Issue by omar2205** [appwrite/pink#50]
### 👟 Reproduction steps

1. Visit https://codepen.io/omar2205/pen/XWBoWKr
2. Open a debug version (https://user-images.githubusercontent.com/1373867/216283364-f2e64c1d-c53f-425e-9eb3-3eb3e5ccf620.png)
3. Switch to responsive / phone

Even if I deleted everything (even the body element), there are still scrollbars.

It's visible even on https://pink.appwrite.io/getting-started (refresh in responsive mode)

**Weirdly enough, this behaviour is only happening in dev tools.** When testing on an actual phone, it's not visible.

### 👍 Expected behavior

There shouldn't be scrollbars

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/1373867/216280848-0a64f169-ff28-41cd-bf6c-840b7d714fa7.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@omar2205 thank you for bringing this up :pray:

**Comment by elad2412** [comment]
Hi @omar2205, we had some fixes to solve this issue.

Please let us know if you find more issues like this in the future.

Closed Issue.

**Comment by omar2205** [comment]
@elad2412 idk, it's still visible
![image](https://user-images.githubusercontent.com/1373867/221748996-4498bee9-f678-44a1-a692-8efa070be5a0.png)

**Comment by omar2205** [comment]
@elad2412 it's fixed
