### ISSUE TITLE
🐛 Bug Report: RTL support: Switch

### ISSUE THREAD

**Issue by omar2205** [appwrite/pink#51]
### 👟 Reproduction steps

Something like this fixes this behaviour

```css
[dir=rtl] .switch:where(:checked)::before {
    transform: translateX(-1rem);
}
```

### 👍 Expected behavior

To be this 
![image](https://user-images.githubusercontent.com/1373867/216288255-01eea019-e923-4c09-b844-450c2c8e8e27.png)

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/1373867/216287272-028122f2-66b8-43ae-8fad-5b0483d08d11.png)
Magic URL dir = 'rtl'
Passowrd dir = 'ltr'

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@omar2205 thank you for submitting this issue :) 

@elad2412 can you take a look at this?

**Comment by elad2412** [comment]
@omar2205 Please take a look :-); the issue is fixed.

If there is ant comment, please let me know.

Issue closed
