### ISSUE TITLE
🐛 Bug Report: Console warning of using 'end' instead 'flex-end'

### ISSUE THREAD

**Issue by ishaanparlikar** [appwrite/pink#58]
### 👟 Reproduction steps

Running app with pink design installed

### 👍 Expected behavior

No Warnings should be generated.

### 👎 Actual Behavior

Console warnings are generating when you use "u-main-end"  or "u-cross-end". Suggest using 

`autoprefixer: end value has mixed support, consider using flex-end instead`

![image](https://user-images.githubusercontent.com/43013132/219585075-99aa2c80-fd82-4200-b4ba-0bd51ee5db41.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by elad2412** [comment]
@ishaanparlikar we are using the new values in our project. The pink design isn't trying to support old browsers' versions. 

We are mainly trying to support those up to one year behind. This is also the reason we are using the new keywords.

Please let us know if you have any other comments.

Issue closed.
