### ISSUE TITLE
🐛 Bug Report: When the Box Model page is opened in 100% screen size, the page exceeds the page and te github stars needs to be updated

### ISSUE THREAD

**Issue by ItsRoy69** [appwrite/pink#66]
### 👟 Reproduction steps

So while I was going through the documentation, and opened this page of Box Model-> https://pink.appwrite.io/utilities/box-model , I see the Github stars were not visible on this particular page in my Edge Browser. 

Thus I can work on this issue. 

### 👍 Expected behavior

![image](https://user-images.githubusercontent.com/78967360/224560464-531bef52-925d-4bc0-96a4-465562a7415d.png)

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/78967360/224560439-7079f395-ce2d-4ffe-af98-9bde88418964.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ItsRoy69** [comment]
I can work on this issue, can someone assign me ?

**Comment by saurabhmehta1601** [comment]
Although , the number of github stars on repository is not getting fetched in real time . Right now the github stars are 272 on github while it shows 270 on website . 

### Stars on website 
![Screenshot (20)](https://user-images.githubusercontent.com/57309205/225686472-5ec43b53-2f7b-4d12-ac59-3e6bd4e9bb20.png)

### Stars on github


 
![Screenshot (19)](https://user-images.githubusercontent.com/57309205/225686557-e2915962-1c37-4c97-baf2-55d8deb9d46f.png)

**Comment by ArmanNik** [comment]
@ItsRoy69 thank you for bringing this up! :pray:

**Comment by ArmanNik** [comment]
@saurabhmehta1601 I believe that the stars are fetched on build and not in realtime to avoid needlessly "hammering" GitHub :laughing: 
Also, I think this issue is related to the screen size and not the browser :+1:

**Comment by saurabhmehta1601** [comment]
> @saurabhmehta1601 I believe that the stars are fetched on build and not in realtime to avoid needlessly "hammering" GitHub 😆 Also, I think this issue is related to the screen size and not the browser 👍

Yes,  I actually misunderstood .

**Comment by TGlide** [comment]
Closing, since it seems to have been fixed.
