### ISSUE TITLE
📚 Documentation: Wrong steps under Setup guidelines in the documentation page

### ISSUE THREAD

**Issue by ItsRoy69** [appwrite/pink#71]
### 💭 Description

When we visit https://github.com/appwrite/pink/blob/main/CONTRIBUTING.md and follow the setup guidelines we see that it instructs us to clone appwrite ui repository eventhough the repository is https://github.com/appwrite/pink, thus this needs to be changed.

![image](https://user-images.githubusercontent.com/78967360/225961544-7685c6b0-a404-4c83-ac5e-6a6e4ee3bb0c.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TGlide** [comment]
Closing since it's been solved :)
