### ISSUE TITLE
🐛 Bug Report: Code not copied

### ISSUE THREAD

**Issue by ashrafchowdury** [appwrite/pink#73]
### 👟 Reproduction steps

On the Home page of the build section, there were two code blocks with the copy button but the copy button doesn't work for some reason.

### 👍 Expected behavior

Copy code when we click on the copy button.

![image](https://user-images.githubusercontent.com/87828904/228516929-a25deda3-aae0-46d4-a87f-cbe5134f361d.png)

### 👎 Actual Behavior

The code doesn't copy when we click on the copy button.

![image](https://user-images.githubusercontent.com/87828904/228515642-15fd7a71-3225-4cd6-b24f-845a283793c9.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ashrafchowdury** [comment]
I can fix this issue, can someone please assign me to work on this issue?

**Comment by joeyouss** [comment]
Hi @ashrafchowdury , thank you for sharing. Please go ahead and make a PR for the same.

**Comment by TGlide** [comment]
Closing, as this has been solved.
