### ISSUE TITLE
🚀 Feature: Allow users to copy icon names by clicking on the icons

### ISSUE THREAD

**Issue by ashrafchowdury** [appwrite/pink#77]
### 🔖 Feature description

To improve the user experience and save time, I propose adding a feature that allows users to **copy the icon names by simply clicking on the icons**. When a user clicks on an icon, the **icon name should be automatically copied to their clipboard**, allowing them to easily paste it wherever they need it.

This feature would not only save time for users but also reduce the likelihood of errors when manually copying icon names. It would make the Pink application more user-friendly and efficient.

### 🎤 Pitch

This feature should be implemented because it would make it much easier and faster for users to work with the Pink application's icons. Currently, users have to manually copy the icon names to use them in code or other applications, which can be a tedious and error-prone process. By allowing users to simply click on an icon to copy its name, we can greatly streamline this workflow and save users time and effort.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi, 
Allow me to talk to my team and get back

**Comment by ashrafchowdury** [comment]
> Hi, 
> Allow me to talk to my team and get back

💯💯💯

**Comment by TGlide** [comment]
@ashrafchowdury Thanks for the issue, love the idea! I assigned it to you 😄

**Comment by joeyouss** [comment]
Hi @ashrafchowdury any update on this? Let us know if you need any help!

**Comment by ashrafchowdury** [comment]
> Hi @ashrafchowdury any update on this? Let us know if you need any help!

I have submitted a PR request.

**Comment by TGlide** [comment]
Closing as this has been solved, with the help of @ashrafchowdury. Thanks!
