### ISSUE TITLE
Roadmap for appwrite pink design

### ISSUE THREAD

**Issue by chhinsras** [appwrite/pink#80]
### 🔖 Feature description

Admin template: dark mode support
More components:

### 🎤 Pitch

It should be good for everyone

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@chhinsras, thanks for creating this issue! 🙏🏼 Would you please provide more details on what you're looking for and create specific issues for each thing you're requesting?

**Comment by chhinsras** [comment]
@stnguyen90 I would like to see something like admin dashboard template. additional components ( sticky tab like windows based)

**Comment by stnguyen90** [comment]
@chhinsras, I don't think we would make an admin dashboard template, but you are welcome to do so. 

If you'd like additional components, please create an issue for each component with a detailed description and then we can see how many upvotes each gets.
