### ISSUE TITLE
Feature request: Adding transform scale(1.01) to the cards under article section

### ISSUE THREAD

**Issue by RajeevDash007** [appwrite/pink#99]
### 👟 Reproduction steps

I want to add the the transform scale (1.01) or making the cards little bigger while hovering, which can make the UI more cool.

### 👍 Expected behavior

It would make the cards little bit bigger while hovering with a smooth transitioning

### 👎 Actual Behavior

While hovering the cards, it does'nt show any effect

![Pink-Design](https://github.com/appwrite/pink/assets/96860040/2509a8e7-5f7c-4092-b49b-e04092c55e36)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by RajeevDash007** [comment]
@joeyouss check it out

**Comment by joeyouss** [comment]
Hi @RajeevDash007 , I appreciate your effort in working on this pull request, but this is not a bug, it is a feature request. However, based on our design considerations, we do not need to scale at this moment. So, we won't be able to merge this pull request right now. Thank you for being so understanding. If you have any further questions or anything else you'd like to contribute, please let us know!

**Comment by joeyouss** [comment]
Thank you so much for understanding!
